<a href="https://colab.research.google.com/github/21IT147/FullStackWebDevelopment_Keval/blob/FullStackWebDevelopment_Keval/21IT147_InternalPracticalExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Import numpy package Create Numpy array numpy_array_1 of 5 X 6 with values in range 3 to 32 Remove the last column and convert it to 5 X 5 Matrix.

In [14]:
import numpy as num

numpy_array_1 = num.arange(3,33).reshape(5,6)

numpy_array_1 = numpy_array_1[:,:5]

print(numpy_array_1)

[[ 3  4  5  6  7]
 [ 9 10 11 12 13]
 [15 16 17 18 19]
 [21 22 23 24 25]
 [27 28 29 30 31]]


Code Description:

Here in this code:

I have imported numpy package as num .

Using arange function I have taken values between 3 and 32 and using reshape function I have given it shape as 5 x 6 matrix.

Then I have selected all rows and first 5 columns from that array.

Then at last I have printed the numpy_array_1.


Create Person Class with following requirements
Create constructor to initialize name,adhar_no.
Create method set_name and get_name to operate with name field of class.
Create method set_adhar and get_adhar to operate with aadhar_no field of class.

In [16]:
class Person:

  def __init__(self):
    self.name = None
    self.adhar_no = None


  def set_name(self,name):
    self.name = name

  def get_name(self):
    return self.name

  def set_adhar(self,adhar_no):
    self.adhar_no = adhar_no

  def get_adhar(self):
    return self.adhar_no



P1 = Person()

P1.set_name("Keval")

P1.set_adhar(985156445936)

print("Name of Person is",P1.get_name(),"and his adhar number is",P1.get_adhar())



Name of Person is Keval and his adhar number is 985156445936


Code Description:

Here in this code:

I have declared class named Person.

I have defined constructor for object creation which initializez values as None

I have defined set_name method which takes self and name as parameter and updated value of name of Person.

I have defined get_name method which takes self as parameter and returns name of that Person.

I have defined set_adhar method which takes self and adhar_no as parameter and updated value of adhar_no of Person.

I have defined get_adhar method which takes self as parameter and returns adhar_no of that Person.

Created P1 as an object of Person.

I have set name of P1 using set_name function.

I have set adhar_no of P1 using set_adhar function.

I have printed name and adhar_no of Person using get_name and get_adhar functions.